module.exports = {
glossary: [
["Actif (asset)", "Élément qui a une valeur et que l'on gère : poste, licence, contrat."],
["Affectation", "Décision de gestion qui attribue un actif à une personne."],
["Agent", "Logiciel installé sur un poste qui remonte son inventaire à l'outil."],
["Approbation", "Autorisation donnée par une personne habilitée avant un changement."],
["Audit (journal d')", "Trace de chaque action : qui, quoi, quand."],
["Catégorie", "Classement d'un ticket pour l'orienter vers la bonne équipe."],
["Changement (change)", "Modification de la production, soumise à évaluation et approbation."],
["CI (élément de configuration)", "Élément dont on suit les dépendances dans la CMDB."],
["Clôture", "Statut final d'un ticket après confirmation de l'utilisateur."],
["CMDB", "Base des éléments de configuration et de leurs relations."],
["Conformité", "Comparaison entre droits achetés et installations constatées."],
["Contournement (workaround)", "Moyen de rétablir le service en attendant la correction définitive."],
["Découverte réseau", "Scan d'une plage d'adresses pour détecter les équipements qui répondent."],
["Demande de service", "Demande de quelque chose de prévu au catalogue."],
["Erreur connue", "Problème dont la cause et le contournement sont documentés."],
["Impact", "Étendue des conséquences d'un incident (personnes, activités)."],
["Incident", "Interruption ou dégradation d'un service."],
["ITAM", "Gestion des actifs informatiques (coûts, licences, contrats, cycle de vie)."],
["ITIL", "Référentiel de bonnes pratiques de gestion des services informatiques."],
["ITSM", "Gestion des services informatiques, vue comme un service rendu."],
["MAC (adresse)", "Identifiant matériel d'une interface réseau."],
["Moindre privilège", "Principe : n'accorder que les droits nécessaires à la fonction."],
["Priorité", "Ordre de traitement déduit de l'impact et de l'urgence."],
["Problème", "Cause inconnue d'un ou plusieurs incidents."],
["RBAC", "Contrôle d'accès fondé sur les rôles."],
["Retour arrière (rollback)", "Plan pour annuler un changement qui échoue."],
["Séparation des tâches", "Le demandeur d'une action n'est pas celui qui l'approuve."],
["SLA", "Accord de niveau de service : délais de prise en charge et de résolution."],
["Urgence", "Délai dans lequel la situation devient critique."],
["Utilisateur connecté", "Personne dont la session est ouverte, remontée par l'agent."],
],
sessions: [
["Séance 1 (2 h)", "Découverte : chapitre 1, TD 1 et 2, TP 1 à 3."],
["Séance 2 (2 h)", "Inventaire : chapitre 2, TD 3, TP 4 à 7."],
["Séance 3 (2 h)", "Inventaire (suite) : TD 4, TP 8 à 10."],
["Séance 4 (2 h)", "Service desk : chapitre 3, TD 5 et 6, TP 11 à 14."],
["Séance 5 (2 h)", "Incidents techniques : chapitre 4, TD 7, TP 15 à 18."],
["Séance 6 (2 h)", "Incident majeur : TD 8, TP 19 et 20."],
["Séance 7 (2 h)", "ITIL approfondi : chapitre 5, TD 9 à 11, TP 21 à 25."],
["Séance 8 (2 h)", "ITAM : chapitre 6, TD 12 et 13, TP 26 à 30."],
["Séance 9 (2 h)", "CMDB : chapitre 7, TD 14, TP 31, 32 et 38."],
["Séance 10 (2 h)", "Administration : chapitre 8, TD 15 à 17, TP 33 à 37 et 39."],
["Séance 11 (2 h)", "Synthèse : TD 18 puis TP 40."],
],
grid: {
head: ["Critère", "Insuffisant", "Fragile", "Satisfaisant", "Très satisfaisant"],
rows: [
["Compréhension des deux vues", "Confond réalité et outil", "Distingue sur des cas simples", "Distingue et prévoit l'effet d'une action", "Anticipe les écarts et propose un contrôle"],
["Méthode de diagnostic", "Agit au hasard", "Suit une méthode avec aide", "Raisonne du simple au complexe, une chose à la fois", "Cherche le point commun et documente"],
["Qualité des tickets et traçabilité", "Descriptions vagues", "Descriptions partielles", "Qui, quoi, où, quand ; solution documentée", "Solution réutilisable, vérification tracée"],
["Respect des processus ITIL", "Contourne", "Applique avec rappels", "Applique le bon processus", "Justifie le choix et ses limites"],
["Droits et traçabilité", "Ne perçoit pas l'enjeu", "Applique sans expliquer", "Applique le moindre privilège", "Anticipe les conflits d'intérêts"],
["Autonomie", "Utilise la solution", "Utilise beaucoup d'indices", "Quelques indices", "Aucun indice ou indice utilisé à bon escient"]]},
};
