// Travaux dirigés (papier / sans simulateur). q = question, a = corrigé guidé (livret enseignant), t = tableau optionnel
module.exports = [
{ n: 1, ch: 1, title: "Incident, demande, problème ou changement ?", duration: "20 min", mode: "Individuel puis correction collective",
  objectif: "Classer sans hésiter les quatre objets ITIL.",
  enonce: ["Pour chaque situation, indiquez s'il s'agit d'un incident, d'une demande de service, d'un problème ou d'un changement. Justifiez en une phrase."],
  qs: [
    { q: "« Mon écran reste noir depuis ce matin. »", a: "**Incident** : un équipement qui fonctionnait ne fonctionne plus." },
    { q: "« Pouvez-vous créer un compte pour notre stagiaire qui arrive lundi ? »", a: "**Demande de service** : on fournit quelque chose de prévu au catalogue (nouvel utilisateur)." },
    { q: "Pour la troisième fois en un mois, le partage réseau « Compta » est inaccessible le lundi matin.", a: "**Problème** : une récurrence dont on cherche la cause racine ; on y rattache les trois incidents." },
    { q: "Le responsable veut remplacer le pare-feu de l'agence par un modèle plus récent.", a: "**Changement** : modification de la production, qui demande évaluation du risque, approbation, plan et retour arrière." },
    { q: "« Je ne peux plus ouvrir ma messagerie. »", a: "**Incident** (compte et accès). Piège : on ne peut pas être sûr avant d'avoir regardé (mot de passe expiré, serveur arrêté…), mais le symptôme est un dysfonctionnement." },
    { q: "« Pouvez-vous installer Visio sur mon poste ? »", a: "**Demande de service** : rien ne dysfonctionne, l'utilisateur demande un logiciel." },
    { q: "Un technicien découvre que le serveur de fichiers est saturé à 98 % et qu'il l'était déjà le mois dernier.", a: "Ce n'est pas encore un incident (rien ne s'est arrêté) : c'est l'amorce d'un **problème** (ou d'une action proactive). Si le disque est plein et que plus personne n'écrit, ce devient un incident. Discuter : un problème peut exister sans incident." },
    { q: "Mettre à jour le firmware du switch cœur un samedi soir.", a: "**Changement** : intervention planifiée sur un équipement critique ; il faut un retour arrière." },
  ] },
{ n: 2, ch: 1, title: "Réalité ou outil ? Deux vues du même SI", duration: "20 min", mode: "Binômes",
  objectif: "Distinguer ce qui existe de ce que l'outil sait.",
  enonce: ["Pour chaque événement, dites s'il modifie la réalité (vue Infrastructure), la connaissance de l'outil (vue ITSM), ou les deux. Précisez ce qu'il faut faire pour que l'outil rattrape la réalité."],
  qs: [
    { q: "On branche un nouveau PC sur le switch.", a: "Réalité seulement. L'outil l'ignore jusqu'à une découverte réseau, un agent ou une saisie." },
    { q: "On saisit un nouveau PC dans l'outil, mais le matériel n'est pas encore livré.", a: "Outil seulement (statut Commandé). La réalité n'a pas changé : il n'existe pas encore." },
    { q: "Un technicien débranche le câble du PC d'Alice.", a: "Réalité seulement. L'outil constatera au mieux que le poste n'est plus joignable (agent muet), sans savoir pourquoi." },
    { q: "Le responsable affecte le PC22 à Chloé dans l'outil.", a: "Outil seulement. L'utilisateur réellement connecté sur le poste est une autre information (remontée par l'agent). Les deux peuvent diverger." },
    { q: "On désinstalle un logiciel interdit sur un poste.", a: "Réalité d'abord. L'outil continue d'afficher l'installation jusqu'à la prochaine remontée d'inventaire." },
    { q: "Le fournisseur renouvelle le contrat de maintenance, et le service achats le saisit dans l'outil.", a: "Les deux (contrat réel et fiche). Si on ne saisit rien, la réalité contractuelle change mais l'outil affiche un contrat expiré." },
  ] },
{ n: 3, ch: 2, title: "Lire et compléter une fiche d'actif", duration: "25 min", mode: "Individuel",
  objectif: "Repérer les informations manquantes et choisir le bon mode d'alimentation.",
  enonce: ["Voici trois fiches d'actifs telles qu'elles apparaissent dans le parc après une découverte réseau seule.",
    "• Fiche A : PC21 — IP 192.168.10.21 — MAC AA:BB:CC:00:00:21 — constructeur Dell — reste vide.",
    "• Fiche B : IMP-COMPTA — IP 192.168.10.50 — MAC AA:BB:CC:00:00:50 — constructeur HP — reste vide.",
    "• Fiche C : SW02 — IP 192.168.10.2 — MAC AA:BB:CC:00:00:02 — constructeur Cisco — reste vide."],
  qs: [
    { q: "Quelles informations de gestion manquent sur chaque fiche ?", a: "Utilisateur affecté, numéro d'inventaire, numéro de série, fin de garantie, localisation, contrat, logiciels (pour le PC). Aucune de ces informations ne se lit sur le réseau." },
    { q: "Pour laquelle de ces fiches peut-on installer un agent ? Pour les autres, que faire ?", a: "Seulement le PC21 (poste avec système d'exploitation). L'imprimante et le switch n'exécutent pas d'agent : saisie manuelle de l'inventaire et du numéro de série, avec un risque de donnée périmée." },
    { q: "Quel champ choisiriez-vous comme identifiant fiable pour éviter les doublons lors d'une nouvelle découverte ? Pourquoi pas le nom ni l'IP ?", a: "L'adresse MAC. Le nom se change, l'IP est souvent attribuée dynamiquement et peut passer d'un équipement à l'autre. Subtilité à évoquer : une MAC peut être usurpée ou changer en cas de remplacement de carte réseau." },
    { q: "Donnez deux informations qu'un agent apporterait sur la fiche A.", a: "Par exemple : modèle et numéro de série matériel, mémoire, système d'exploitation, logiciels installés, utilisateur connecté, date de dernier contact." },
    { q: "Pourquoi une donnée saisie manuellement sur la fiche B est-elle plus fragile ?", a: "Rien ne la met à jour : si l'imprimante change d'emplacement ou de numéro de série, la fiche devient fausse sans alerte. On prévoit une revue périodique." },
  ] },
{ n: 4, ch: 2, title: "Agent en erreur : trois pannes, trois causes", duration: "25 min", mode: "Groupes de 3",
  objectif: "Diagnostiquer avant d'agir.",
  enonce: ["Le tableau de bord affiche trois postes qui ne remontent plus :",
    "• Poste 1 : dernier contact il y a 3 minutes, mais l'inventaire date de 12 jours.",
    "• Poste 2 : dernier contact il y a 2 jours, le service « agent » est à l'arrêt.",
    "• Poste 3 : dernier contact il y a 5 heures, le poste est allumé mais son câble réseau est débranché."],
  qs: [
    { q: "Pour chaque poste, formulez l'hypothèse la plus probable.", a: "Poste 1 : l'agent tourne mais n'envoie plus d'inventaire complet (inventaire obsolète) : relancer une remontée. Poste 2 : agent arrêté : le redémarrer et comprendre pourquoi il s'est arrêté. Poste 3 : agent bloqué faute de réseau : rétablir le lien, l'agent remontera seul." },
    { q: "Quelle action NE FAUT-IL PAS faire en premier sur le poste 3 ?", a: "Réinstaller l'agent : la cause est le réseau, pas l'agent. Réinstaller masque l'origine et perd du temps." },
    { q: "Comment vérifiez-vous que la réparation a réussi ?", a: "Un nouvel inventaire est reçu avec une date récente ; on contrôle sur la fiche (date de remontée, données à jour), pas seulement l'absence d'erreur." },
    { q: "Que proposeriez-vous pour détecter ces cas plus tôt ?", a: "Une alerte quand le dernier inventaire dépasse un seuil (par exemple 7 jours), un tableau de bord des agents muets, une revue hebdomadaire." },
  ] },
{ n: 5, ch: 3, title: "Réécrire un mauvais ticket", duration: "25 min", mode: "Individuel",
  objectif: "Transformer un appel en ticket exploitable (qui, quoi, où, quand).",
  enonce: ["Voici trois notes prises à la hâte par un agent. Réécrivez chacune en un titre et une description exploitables, et indiquez quelles questions vous auriez dû poser à l'appelant."],
  qs: [
    { q: "« Ça marche plus. » (Appel de Bruno Leroy, Production)", a: "Notes insuffisantes. Questions à poser : qu'est-ce qui ne marche plus (poste, imprimante, application) ? depuis quand ? message d'erreur ? qu'avez-vous fait avant ? sur quel poste (PC21) ? Exemple de réécriture une fois les réponses obtenues : « PC21 : impossible d'ouvrir le logiciel de planning depuis 8 h 30, message “licence introuvable”. Bruno Leroy, Production. »" },
    { q: "« Internet lent. » (Appel de Chloé Dubois, Commercial)", a: "Quantifier : lent depuis quand, pour tout ou pour certains sites, câble ou Wi-Fi, les collègues aussi ? Si les collègues sont aussi touchés, l'impact est plus large (voir TD8). Réécriture type : « PC22 : navigation très lente depuis 14 h (page de 30 s), toutes applications web, câble. Collègues du plateau signalent la même chose. »" },
    { q: "« Imprimante ne marche pas, urgent !!! » (Appel d'Alice Martin, Comptabilité)", a: "« Urgent » n'est pas une information : demander quelle échéance, combien de personnes touchées, quelle imprimante, quel message, quelle activité bloquée. Réécriture : « IMP-COMPTA : les factures ne s'impriment plus depuis 10 h (la file d'attente reste bloquée), échéance de facturation à 17 h, toute la comptabilité impactée. »" },
    { q: "Quel est l'intérêt de lier le ticket à un équipement dès la création ?", a: "Retrouver l'état réel de l'équipement, son historique d'incidents, son contrat, son utilisateur ; repérer les pannes récurrentes ; alimenter la gestion des problèmes." },
  ] },
{ n: 6, ch: 3, title: "Calculer la priorité", duration: "20 min", mode: "Individuel puis correction",
  objectif: "Appliquer la matrice impact × urgence, et la discuter.",
  enonce: ["Utilisez la matrice du chapitre 3 (§3.3). Pour chaque ticket, donnez l'impact, l'urgence, la priorité et justifiez."],
  qs: [
    { q: "La messagerie est coupée pour toute l'entreprise (45 personnes), aucune échéance particulière.", a: "Impact élevé (toute l'entreprise). Urgence élevée (activité bloquée). **P1**. Un cas de contexte : même sans échéance, l'arrêt d'un outil d'usage général justifie l'urgence." },
    { q: "Le poste d'un stagiaire plante une fois par jour, il travaille sur autre chose.", a: "Impact faible, urgence faible : **P4**." },
    { q: "Le serveur de facturation est arrêté, nous sommes le 30 du mois (jour de facturation).", a: "Impact élevé (comptabilité), urgence élevée (échéance du jour) : **P1**." },
    { q: "Une imprimante de couloir est en panne, il en reste deux autres à 10 mètres.", a: "Impact faible (contournement immédiat), urgence faible : **P4**." },
    { q: "Le poste du directeur commercial ne démarre plus, il a un rendez-vous client dans 2 heures.", a: "Impact moyen (une personne mais fonction clé) ; urgence élevée (échéance dans 2 h) : **P2**. Débat : certains classent l'impact en « élevé » pour un dirigeant. Le référentiel de l'entreprise doit trancher, pas l'intuition de l'agent (c'est aussi une question d'équité)." },
    { q: "Un utilisateur demande le changement de la couleur de son fond d'écran.", a: "Demande de service, pas un incident : on ne calcule pas de priorité de la même façon ; la priorité sera faible. Faire noter qu'une demande ne suit pas le même circuit." },
  ] },
{ n: 7, ch: 4, title: "Arbre de diagnostic par couches", duration: "30 min", mode: "Groupes de 3",
  objectif: "Appliquer la méthode « du plus simple au plus complexe ».",
  enonce: ["Pour chaque symptôme, proposez la liste ordonnée de vos vérifications (cinq au plus), en justifiant l'ordre."],
  qs: [
    { q: "Le PC d'Alice « n'a plus de réseau ».", a: "1) Voyant et câble au poste et à la prise : le câble est-il branché ? 2) Le poste est-il alimenté ? 3) Le port du switch est-il actif ? 4) Autres postes du même switch touchés ? 5) Configuration IP. L'ordre va du physique au logique, du plus rapide au plus long. (Dans InfraLab : câble débranché.)" },
    { q: "Le logiciel de facturation ne répond plus pour toute la comptabilité.", a: "1) Combien de personnes touchées ? (toute la comptabilité → côté serveur) 2) Le serveur SRV-FACT est-il allumé et joignable ? 3) Le service applicatif tourne-t-il ? 4) Dernier changement sur ce serveur ? 5) Journaux. Le point commun est le serveur." },
    { q: "Trois postes hors ligne au même moment, dans le même bâtiment.", a: "1) Chercher l'équipement commun (le switch qui les relie). 2) Est-il alimenté ? 3) Les liens montants sont-ils actifs ? Corriger la cause commune plutôt que traiter les trois postes séparément." },
    { q: "Une seule personne ne peut plus se connecter à sa messagerie, les autres oui.", a: "1) Mot de passe expiré ou compte verrouillé ? 2) Le poste atteint-il le serveur ? 3) Profil local ? On remonte du compte (individuel) vers le service : l'impact est limité à une personne, donc le point commun n'est pas le serveur." },
    { q: "Pourquoi ne faut-il changer qu'une chose à la fois ?", a: "Pour savoir ce qui a corrigé la panne (ou l'a aggravée). Si l'on change trois choses et que ça remarche, on ne sait pas quoi retenir pour l'article de connaissance." },
  ] },
{ n: 8, ch: 4, title: "Incident majeur : établir l'ordre d'intervention", duration: "30 min", mode: "Groupes de 4",
  objectif: "Prioriser, regrouper, communiquer.",
  enonce: ["Lundi 9 h, le switch cœur du siège est éteint. Quatre tickets sont déjà ouverts :",
    "T1 — Comptabilité : « plus de logiciel de facturation, clôture mensuelle à 12 h ». T2 — Commercial : « le partage de fichiers est inaccessible ». T3 — Accueil : « l'imprimante du hall ne répond plus ». T4 — Direction : « plus de messagerie ».",
    "Vous disposez d'un technicien."],
  qs: [
    { q: "Quelle est la cause commune probable ? Comment la confirmez-vous en une minute ?", a: "Le switch cœur (SW-SIEGE-01) : les quatre symptômes sont des pertes de réseau. On le confirme en regardant s'il est alimenté / s'il répond, et si les postes affectés sont tous derrière lui." },
    { q: "Dans quel ordre agissez-vous ?", a: "1) Rallumer / rétablir le switch (une action qui résout probablement les quatre tickets). 2) Vérifier chaque service. 3) Résoudre et documenter T1 en premier (échéance 12 h), puis T4, T2 et T3. Ne pas traiter les tickets un à un avant d'avoir rétabli la cause." },
    { q: "Attribuez une priorité à chacun.", a: "T1 P1 (échéance du jour, comptabilité). T4 P2 ou P1 selon l'organisation (direction, messagerie générale). T2 P2/P3. T3 P4 (imprimante du hall). Accepter des variantes si elles sont argumentées par impact et urgence." },
    { q: "Rédigez le message de communication aux utilisateurs.", a: "Un message court : constat (« le réseau du siège est coupé »), cause connue ou en cours d'analyse, action en cours, prochaine information à heure fixe. Il est posté sur le ticket principal et rattaché aux autres." },
    { q: "Que reste-t-il à faire une fois le service rétabli ?", a: "Documenter, vérifier auprès des utilisateurs, clore ; ouvrir un problème pour comprendre pourquoi le switch s'est éteint (alimentation ? onduleur ?) ; éventuellement un changement pour sécuriser l'alimentation." },
  ] },
{ n: 9, ch: 5, title: "Calculer les SLA", duration: "30 min", mode: "Individuel",
  objectif: "Calculer des délais, gérer la suspension.",
  enonce: ["On utilise les cibles du chapitre 5 (§5.1) et un calendrier 24 h/24, 7 j/7 (comme dans InfraLab). Pour chaque ticket, indiquez si les délais de prise en charge et de résolution sont respectés.",
    "A — P1, créé à 09:00, pris en charge à 09:12, résolu à 12:30.",
    "B — P3, créé à 10:00, pris en charge à 10:20, en attente de l'utilisateur de 11:00 à 14:00, résolu à 15:30 (même jour).",
    "C — P2, créé à 08:00, pris en charge à 09:30, résolu à 15:00.",
    "D — P4, créé lundi 09:00, pris en charge lundi 11:00, résolu jeudi 08:00."],
  qs: [
    { q: "Ticket A", a: "Prise en charge : 12 min ≤ 15 min, respectée. Résolution : 3 h 30 ≤ 4 h, respectée (à risque car > 75 % du délai : 3 h)." },
    { q: "Ticket B", a: "Prise en charge : 20 min ≤ 4 h. Temps utile de résolution : 5 h 30 − 3 h de suspension = 2 h 30 ≤ 24 h. Respecté. La suspension ne compte pas, car le service attendait l'utilisateur." },
    { q: "Ticket C", a: "Prise en charge : 1 h 30 > 1 h : **dépassée**. Résolution : 7 h ≤ 8 h : respectée. Un SLA peut être dépassé sur un volet et tenu sur l'autre." },
    { q: "Ticket D", a: "Prise en charge : 2 h ≤ 8 h. Résolution : du lundi 09:00 au jeudi 08:00 = 71 h ≤ 72 h : respectée de justesse." },
    { q: "Un technicien ouvre le ticket A et note « pris en charge » à 10:00 sans rien faire. Est-ce honnête ? Quels indicateurs risquent d'être faussés ?", a: "Non : c'est « jouer avec l'horloge ». Le SLA devient un chiffre cosmétique qui ne mesure plus le service rendu. À discuter : la mesure doit refléter une action réelle (diagnostic engagé, utilisateur contacté)." },
    { q: "Pourquoi un ticket mal qualifié (mauvais impact/urgence) fausse-t-il le SLA ?", a: "La priorité détermine la cible : un P1 déclaré P4 aura 72 h, donc le délai « respecté » ne reflète pas le besoin réel." },
  ] },
{ n: 10, ch: 5, title: "Du ticket au problème", duration: "30 min", mode: "Groupes de 3",
  objectif: "Détecter une récurrence et rédiger une fiche problème.",
  enonce: ["Trois incidents clos cette semaine : INC-101 (lundi) « PC Compta sans réseau », INC-107 (mercredi) « PC Compta sans réseau », INC-112 (vendredi) « PC Compta sans réseau ». À chaque fois, le technicien a rebranché le câble, noté « câble rebranché » et clos.",
    "Complétez la fiche : problème / incidents rattachés / cause racine hypothétique / contournement / correction définitive."],
  qs: [
    { q: "Pourquoi un problème et pas un quatrième incident ?", a: "Parce que la solution est un contournement : le service est rétabli mais la cause n'est pas traitée. Le problème sert à traiter la cause et éviter le prochain incident." },
    { q: "Proposez une cause racine plausible.", a: "Câble ou prise défectueux (connecteur lâche), goulotte qui tire sur le câble, nettoyage passant le long du bureau. On cherche ce qui explique la périodicité. L'hypothèse est à vérifier, pas à affirmer." },
    { q: "Quel contournement documenter ?", a: "« Rebrancher le câble sur la prise murale n° X, vérifier le voyant, tester l'accès au serveur. » Le contournement est la procédure qui rétablit rapidement en attendant la correction." },
    { q: "Quelle correction définitive proposer ? Est-ce un changement ?", a: "Remplacer le câble et la prise, fixer le câble. Oui : toute intervention sur la production passe par un changement (même mineur, de risque faible et sans approbation lourde)." },
    { q: "Quel indicateur montre que le problème est résolu ?", a: "Aucun nouvel incident de ce type sur une période de référence (par exemple 30 jours)." },
  ] },
{ n: 11, ch: 5, title: "Rédiger un dossier de changement", duration: "35 min", mode: "Binômes",
  objectif: "Formuler risque, plan, retour arrière, vérification.",
  enonce: ["Le switch SW02 (24 ports) est défaillant : il perd des paquets. Il dessert 12 postes du bâtiment B. Un switch de remplacement est en stock. Rédigez le dossier de changement."],
  qs: [
    { q: "Quel est le risque principal ? Évaluez-le (faible / moyen / élevé) et justifiez.", a: "Risque moyen à élevé : coupure du réseau de 12 postes pendant l'intervention ; la configuration doit être reproduite fidèlement. Un risque est jugé selon sa probabilité et ses conséquences." },
    { q: "Rédigez le plan d'intervention en 6 étapes.", a: "1) Prévenir les utilisateurs et fixer un créneau (début de soirée). 2) Sauvegarder la configuration de SW02. 3) Étiqueter les câbles. 4) Remplacer le switch. 5) Restaurer la configuration. 6) Tester la connectivité des 12 postes." },
    { q: "Rédigez le retour arrière.", a: "Si la connectivité n'est pas rétablie après 30 minutes, remettre l'ancien SW02 (conservé), restaurer son état d'origine, et reporter le changement. Un retour arrière sans critère de déclenchement n'est pas un plan." },
    { q: "Qui doit approuver et pourquoi pas le demandeur ?", a: "Le responsable (rôle habilité). Le demandeur ne se contrôle pas lui-même : séparation des tâches." },
    { q: "Comment vérifiez-vous que le changement est réussi ?", a: "Tous les postes sont de nouveau joignables, l'inventaire est à jour, aucune alerte sur le switch, les utilisateurs ont confirmé. On consigne le résultat." },
    { q: "Ce changement doit-il passer par un changement « urgent » (procédure accélérée) ?", a: "Cela dépend du contexte : si les 12 postes sont déjà coupés, on est dans l'urgence (changement urgent). Si la panne est partielle, on planifie. L'urgence ne supprime pas l'approbation, elle l'accélère." },
  ] },
{ n: 12, ch: 6, title: "Conformité des licences", duration: "30 min", mode: "Individuel",
  objectif: "Calculer, interpréter, décider.",
  enonce: ["NovaTech possède les droits et installations suivants :"],
  table: { head: ["Logiciel", "Licences achetées", "Installations constatées", "Politique"], rows: [["Microsoft Office", "3", "4", "Autorisé"], ["Windows 11 Pro", "10", "10", "Autorisé"], ["Visio", "2", "1", "Autorisé"], ["TeamViewer", "0", "1", "Interdit"]], widths: [2400, 2000, 2400, 2226] },
  qs: [
    { q: "Complétez la conformité de chaque logiciel.", a: "Office : −1 (non conforme, une installation sans droit). Windows : 0 (conforme, aucune marge). Visio : +1 (conforme, une licence inutilisée). TeamViewer : installation interdite, hors de la comptabilité de licence." },
    { q: "Pour Office, quelles sont les deux issues légitimes ? Laquelle choisir ?", a: "Acheter une licence supplémentaire, ou désinstaller sur l'un des postes. Le choix dépend du besoin : si le poste en question utilise réellement Office, on achète ; sinon on désinstalle. Ne jamais « régulariser » en modifiant le nombre dans l'outil." },
    { q: "Que proposez-vous pour Visio ?", a: "Réaffecter la licence inutilisée ou ne pas la renouveler : c'est une économie potentielle." },
    { q: "TeamViewer est interdit : quelles sont les actions et quelle trace garder ?", a: "Désinstaller sur le poste, relancer un inventaire pour confirmer, vérifier qui l'a installé et pourquoi (droits administrateur trop larges ?), tracer dans le ticket." },
    { q: "Pourquoi le chiffre « 4 installations » peut-il être faux ?", a: "L'outil ne connaît que les postes équipés d'un agent et à jour. Un poste sans agent ou à l'inventaire obsolète fausse le compte. Il faut s'assurer de la couverture de l'inventaire avant de conclure." },
  ] },
{ n: 13, ch: 6, title: "Contrats et échéances", duration: "25 min", mode: "Individuel",
  objectif: "Lire un tableau d'échéances et décider.",
  enonce: ["Nous sommes le 15 mars. Règle du TD : un contrat est « proche de l'échéance » à moins de 60 jours, « expiré » après la date."],
  table: { head: ["Contrat", "Fournisseur", "Objet", "Échéance", "Actifs rattachés"], rows: [["CTR-01", "NetSupport", "Maintenance switches", "30 avril", "SW02"], ["CTR-02", "CloudSoft", "Abonnement messagerie", "28 février", "—"], ["CTR-03", "HP", "Garantie imprimantes", "15 décembre", "IMP-COMPTA"]], widths: [1100, 1700, 2600, 1700, 1926] },
  qs: [
    { q: "Pour chaque contrat, donnez son état et la décision attendue.", a: "CTR-01 : échéance dans 46 jours → proche, décision à prendre (renouveler ? renégocier ?). CTR-02 : expiré depuis 15 jours → agir tout de suite (service sans cadre contractuel). CTR-03 : dans 9 mois → rien à faire, mais à surveiller." },
    { q: "Pourquoi CTR-02 n'a-t-il aucun actif rattaché ? Est-ce normal ?", a: "C'est un abonnement de service (messagerie), pas du matériel : il n'est pas rattaché à un actif mais à un service. Question ouverte : on pourrait le lier à la CMDB (service Messagerie)." },
    { q: "Un switch tombe en panne le 20 mai. Que perd-on si CTR-01 n'est pas renouvelé ?", a: "La maintenance : plus de remplacement garanti ni d'assistance du fournisseur, donc des délais et des coûts de remplacement supportés par NovaTech." },
    { q: "Qui doit être alerté de l'échéance et quand ?", a: "Le gestionnaire de contrats, bien avant le seuil (préavis de résiliation ou de renouvellement), souvent 90 jours. Une alerte à 60 jours laisse peu de temps pour une négociation." },
  ] },
{ n: 14, ch: 7, title: "Analyse d'impact sur un schéma de dépendances", duration: "30 min", mode: "Groupes de 3",
  objectif: "Suivre les dépendances et en déduire l'impact.",
  enonce: ["Dépendances de NovaTech (flèche = « dépend de ») :",
    "Service Paie → Logiciel de paie → SRV-ITSM. Service Facturation → PC-COMPTA-01 ; Service Facturation → IMP-COMPTA. PC-COMPTA-01 est connecté à SW02 ; IMP-COMPTA est connectée à SW02 ; SW02 est connecté à SW-SIEGE-01."],
  qs: [
    { q: "SRV-ITSM est arrêté. Quels services sont touchés ?", a: "Le Logiciel de paie (dépendance directe), puis le service Paie (par rebond). Facturation n'est pas touché." },
    { q: "SW02 tombe. Quels services sont touchés ?", a: "Facturation comptable (via PC-COMPTA-01 et IMP-COMPTA qui perdent leur connexion). L'impact est indirect : il passe par la connectivité." },
    { q: "SW-SIEGE-01 tombe. Même question.", a: "SW02 perd sa liaison montante, donc PC-COMPTA-01 et IMP-COMPTA aussi : Facturation touché. Selon la topologie, SRV-ITSM peut être touché aussi (s'il passe par SW-SIEGE-01) : le schéma du TD ne le dit pas, d'où l'intérêt de la CMDB complète." },
    { q: "Quelle relation manque si l'on veut que la panne de SRV-ITSM soit répercutée sur la Paie ?", a: "« Service Paie dépend du Logiciel de paie » : sans cette relation saisie, la CMDB ne peut pas faire le lien. C'est le piège du TP 38." },
    { q: "Pourquoi cette analyse est-elle utile avant un changement ?", a: "Elle indique ce qui sera touché par l'intervention, donc qui prévenir, quand intervenir et quel risque inscrire au dossier." },
  ] },
{ n: 15, ch: 8, title: "Concevoir une matrice de droits", duration: "35 min", mode: "Groupes de 4",
  objectif: "Appliquer le moindre privilège.",
  enonce: ["Cochez dans le tableau les permissions que vous accorderiez à chaque rôle (U = Utilisateur, T = Technicien, R = Responsable, A = Administrateur). Justifiez deux choix.",
    "Permissions : ouvrir un ticket ; qualifier un ticket ; attribuer un ticket ; résoudre un ticket ; approuver un changement ; modifier le cycle de vie d'un actif ; gérer les contrats ; gérer les utilisateurs ; gérer les rôles ; consulter le journal d'audit."],
  table: { head: ["Permission", "U", "T", "R", "A"], rows: [["Ouvrir un ticket", "", "", "", ""], ["Qualifier un ticket", "", "", "", ""], ["Attribuer un ticket", "", "", "", ""], ["Résoudre un ticket", "", "", "", ""], ["Approuver un changement", "", "", "", ""], ["Modifier le cycle de vie d'un actif", "", "", "", ""], ["Gérer les contrats", "", "", "", ""], ["Gérer les utilisateurs", "", "", "", ""], ["Gérer les rôles", "", "", "", ""], ["Consulter le journal d'audit", "", "", "", ""]], widths: [4626, 1100, 1100, 1100, 1100] },
  qs: [
    { q: "Proposition de matrice (justifiez deux choix de votre groupe).", a: "Une matrice de référence (à adapter) : Ouvrir un ticket : U T R A. Qualifier : T R (A selon l'organisation). Attribuer : T R. Résoudre : T. Approuver un changement : R. Cycle de vie d'actif : T (limité) / R. Contrats : R. Utilisateurs : A. Rôles : A. Journal d'audit : A (et R en lecture). Accepter toute matrice défendue par le moindre privilège ; ne pas accepter « tout à tout le monde »." },
    { q: "Pourquoi l'administrateur n'a-t-il pas forcément le droit de résoudre les tickets ?", a: "Séparation des fonctions : celui qui gère les droits n'exploite pas l'outil au quotidien, pour qu'un compte à privilèges ne soit pas aussi un compte « de production »." },
    { q: "Un utilisateur ordinaire peut-il voir tous les tickets ?", a: "Non : il ne voit que les siens (confidentialité). Un ticket peut contenir des informations sensibles." },
    { q: "Que se passe-t-il si l'on retire à tort « ouvrir un ticket » au rôle Utilisateur ?", a: "Plus personne ne peut déclarer un incident via l'outil : c'est une erreur grave, d'où la vérification « les utilisateurs peuvent toujours ouvrir un ticket » du TP 39." },
  ] },
{ n: 16, ch: 8, title: "Séparation des tâches : situations", duration: "25 min", mode: "Débat",
  objectif: "Identifier les conflits d'intérêts et proposer une solution.",
  enonce: ["Pour chaque situation, dites si la séparation des tâches est respectée. Sinon, proposez une correction."],
  qs: [
    { q: "David a demandé le remplacement du switch et l'a approuvé lui-même.", a: "Non respectée. Il faut qu'un responsable (Éric) approuve." },
    { q: "Léa (administratrice) crée le compte de Karim et lui attribue le rôle Technicien.", a: "Respectée : c'est exactement son rôle d'administrer les comptes." },
    { q: "Léa attribue elle-même le ticket urgent à Karim.", a: "Non respectée : Léa gère les droits, elle ne devrait pas exploiter les tickets. Un technicien ou un responsable le fait." },
    { q: "Un technicien peut aussi modifier le prix d'achat dans la fiche d'un actif.", a: "Discutable et à éviter : la valeur financière n'est pas utile à son travail et peut fausser l'amortissement ; réserver au responsable." },
    { q: "Le seul administrateur quitte l'entreprise, et son compte est désactivé immédiatement.", a: "Dangereux : plus aucun administrateur. L'outil refuse de désactiver le dernier admin ; il faut en nommer un autre avant." },
  ] },
{ n: 17, ch: 8, title: "Lire un journal d'audit", duration: "25 min", mode: "Individuel",
  objectif: "Reconstituer une chronologie et juger de la légitimité.",
  enonce: ["Extrait du journal d'audit de NovaTech :"],
  table: { head: ["Date et heure", "Auteur", "Action"], rows: [["09/10 08:42", "Léa Garnier", "Création du compte Karim Benali"], ["09/10 08:45", "Léa Garnier", "Ajout du rôle Technicien à Karim Benali"], ["09/10 09:10", "Karim Benali", "Qualification du ticket INC-0007"], ["09/10 11:32", "Bruno Leroy", "Modification du coût d'achat de PC21 : 1 200 € → 1 €"], ["09/10 11:40", "Bruno Leroy", "Consultation de la fiche PC22"], ["09/10 14:05", "Éric Moreau", "Approbation du changement CHG-0003"]], widths: [2000, 2200, 4826] },
  qs: [
    { q: "Quelle ligne vous paraît suspecte et pourquoi ?", a: "11:32 : Bruno est un utilisateur ordinaire (rôle Utilisateur), il ne devrait pas pouvoir modifier une donnée financière d'un actif. La modification est aussi anormale (1 200 € → 1 €)." },
    { q: "Que peut-on affirmer et que ne peut-on pas affirmer sur Bruno ?", a: "On peut affirmer que le compte de Bruno a fait la modification. On ne peut pas affirmer qu'il en est l'auteur humain (compte partagé, session laissée ouverte). Prudence : le journal prouve une action, pas une intention." },
    { q: "Quelle correction immédiate ?", a: "Rétablir le coût à 1 200 € et consigner la correction (tracé). Ne pas effacer la ligne du journal : l'historique est la preuve." },
    { q: "Quelle mesure pour éviter la récidive ?", a: "Corriger les droits du rôle (retirer la modification des actifs à Utilisateur), vérifier les autres permissions, programmer une revue périodique et garder le journal activé." },
    { q: "Pourquoi la ligne de 11:40 est-elle anodine ?", a: "Une consultation de fiche est normale pour un utilisateur ; ce qui compte est l'écart entre l'action et le rôle." },
  ] },
{ n: 18, ch: 0, title: "Étude de cas de synthèse : un lundi matin chez NovaTech", duration: "60 min", mode: "Groupes de 4, restitution orale de 5 minutes",
  objectif: "Mobiliser l'ensemble de la démarche ITSM.",
  enonce: ["Lundi 8 h 15. Vous êtes l'administrateur ITSM. Trois collègues (Alice, Bruno, Chloé) n'ont plus de réseau. Le parc est partiel : seulement deux postes sur quatre ont un agent. La licence Office compte 3 droits pour 4 installations. Karim, nouveau technicien, n'a pas encore de compte. Éric, responsable, est absent jusqu'à 10 h.",
    "Rédigez un plan d'action chronologique qui couvre : le rétablissement, la qualité des tickets, le problème sous-jacent, le changement nécessaire, la conformité, l'accueil de Karim, et la traçabilité."],
  qs: [
    { q: "Quelle est votre première action et pourquoi ?", a: "Chercher la cause commune des trois pannes (switch ?), la rétablir, avant de traiter les tickets un à un." },
    { q: "Comment organisez-vous les tickets ?", a: "Liés à chaque poste, qualifiés (impact, urgence), solution documentée, vérification auprès de chaque utilisateur, puis clôture. Dans InfraLab : TP 19 et 40." },
    { q: "Comment traitez-vous la cause profonde ?", a: "Un problème regroupant les trois incidents, cause racine documentée ; un changement (remplacement du switch) soumis à l'approbation d'Éric : on attend son retour, on ne l'approuve pas à sa place." },
    { q: "Que faites-vous pour la conformité d'Office ?", a: "Installer l'agent sur les postes manquants pour fiabiliser le compte, puis déclarer les droits et décider : acheter un droit ou désinstaller." },
    { q: "Quels droits donnez-vous à Karim ?", a: "Utilisateur et Technicien, sans rôle d'administration : le minimum utile." },
    { q: "Comment prouverez-vous votre travail ?", a: "Par le journal d'audit et les traces dans les tickets (qui a fait quoi, quand), complétées par le compte rendu exportable du TP 40." },
  ] },
];
