/** Catalogue des événements d'infrastructure (cf. ARCHITECTURE.md §5.2). */
export const EV = {
  DeviceAdded: 'DeviceAdded',
  DeviceRemoved: 'DeviceRemoved',
  DeviceMoved: 'DeviceMoved',
  DeviceReplaced: 'DeviceReplaced',
  CableConnected: 'CableConnected',
  CableDisconnected: 'CableDisconnected',
  DevicePoweredOn: 'DevicePoweredOn',
  DevicePoweredOff: 'DevicePoweredOff',
  DeviceOnline: 'DeviceOnline',
  DeviceOffline: 'DeviceOffline',
  IPAddressChanged: 'IPAddressChanged',
  HardwareChanged: 'HardwareChanged',
  ItsmServerSet: 'ItsmServerSet',
  SoftwareInstalled: 'SoftwareInstalled',
  SoftwareRemoved: 'SoftwareRemoved',
  UserSessionChanged: 'UserSessionChanged',
  VmHostChanged: 'VmHostChanged',
} as const;
